apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-validacion-mysqlserver-deployment
  namespace: ingress-basic
  #namespace: rds-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-validacion-mysql
  template:
    metadata:
      labels:
        app: api-validacion-mysql
        name: api-validacion-mysqlserver-deployment
    spec:
      hostname: emailvalidation-mysql
      containers:
      - name: emailvalidation-mysql
        image: mysql:8.0.19
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
          - containerPort: 3306
        envFrom:
          - secretRef:
              name: mysql-secret