apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-deployment
  namespace: ingress-basic
  #namespace: rds-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bi
  template:
    metadata:
      name: bi-deployment
      labels:
        app: bi
    spec:
      hostname: bi
      containers:
        - name: bi
          #image: jpinargoteb/web_apiservice:v9.1
          image: jpinargoteb/web_apiservice:v10.3
          ports:
            - containerPort: 5050