apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bi-azure-disk
  namespace: ingress-rds
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bi-sql-data
  namespace: ingress-rds
  annotations:
    volume.beta.kubernetes.io/storage-class: bi-azure-disk
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 2Gi