apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ingress-basic
  #namespace: rds-prod
  labels:
    app: mysql
type: Opaque
data:
  MYSQL_DATABASE: ZGJDb3JyZW9z
  MYSQL_ROOT_PASSWORD: QWRtaW4uMjA4MA==