apiVersion: v1
kind: Service
metadata:
  name: bi-service
  namespace: ingress-basic
  #namespace: rds-prod
  labels:
    app: bi
spec:
  #type: ClusterIP
  #type: LoadBalancer
  ports:
    - port: 80
      #8050
      targetPort: 5050
      #nodePort: 30874
  selector:
    app: bi