apiVersion: v1
kind: Service
metadata:
  name: api-validacion-service
  namespace: ingress-basic
  #namespace: rds-prod
  labels:
    app: api-validacion
spec:
  #type: ClusterIP
  #type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 32493
  selector:
    app: api-validacion