apiVersion: v1
kind: Service
metadata:
  name: bi-service
  namespace: rds-prod
  labels:
    app: bi
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
    - port: 8050
      targetPort: 5050
      #nodePort: 30874
  selector:
    app: bi