apiVersion: v1
kind: Service
metadata:
  name: api-validacion-mysqlserver-service
  namespace: ingress-basic
  #namespace: rds-prod
  labels:
    app: api-validacion-mysqlserver-service
spec:
  #type: ClusterIP
  #type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
      #nodePort: 31297
  selector:
    app: api-validacion-mysql
    #name: api-validacion-mysqlserver-deployment