apiVersion: v1
kind: Service
metadata:
  name: frontend-bi-service
  namespace: ingress-rds
  labels:
    app: frontend-bi
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 6050 
      #nodePort: 30785
  selector:
    app: frontend-bi