apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarviz-mssql-deployment
  namespace: yarviz-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarvizprod
  template:
    metadata:
      labels:
        app: yarvizprod
    spec:
      #terminationGracePeriodSeconds: 30
      hostname: yarvizprod
      #securityContext:
        #fsGroup: 10001
      containers:
      - name: mssql-yarviz
        image: mcr.microsoft.com/mssql/server:2017-CU27-ubuntu-16.04
        #resources:
          #limits:
            #memory: "7Gi"
        ports:
          - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yarviz-sql-secret
              key: SA_PASSWORD
        - name: MSSQL_AGENT_ENABLED
          value: "true"
        - name: MSSQL_BACKUP_DIR
          value: "/backup/"
        volumeMounts:
          - name: yarviz-sqldb
            mountPath: /var/opt/mssql
      volumes:
        - name: yarviz-sqldb
          persistentVolumeClaim:
            claimName: yarviz-sql-data