apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarap-mssql-deployment
  namespace: yarviz-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarapprod
  template:
    metadata:
      labels:
        app: yarapprod
    spec:
      terminationGracePeriodSeconds: 30
      hostname: yarapprod
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql-yarap
        image: mcr.microsoft.com/mssql/server:2017-CU27-ubuntu-16.04
        ports:
          - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yarap-sql-secret
              key: SA_PASSWORD
        - name: MSSQL_AGENT_ENABLED
          value: "true"
        - name: MSSQL_BACKUP_DIR
          value: "/backup/"
        volumeMounts:
          - name: yarap-sqldb
            mountPath: /var/opt/mssql
      volumes:
        - name: yarap-sqldb
          persistentVolumeClaim:
            claimName: yarap-sql-data