apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: yarap-azure-disk
  namespace: yarviz-prod
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yarap-sql-data
  namespace: yarviz-prod
  annotations:
    volume.beta.kubernetes.io/storage-class: yarap-azure-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi