apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk
  namespace: ingress-yarviz-prod
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-data
  namespace: ingress-yarviz-prod
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 40Gi