apiVersion: v1
kind: Service
metadata:
  name: api-yarap-service
  namespace: yarviz-prod
  labels:
    app: api-yarap
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
    - port: 4050
      targetPort: 4050
      #nodePort: 32493
  selector:
    app: api-yarap