apiVersion: v1
kind: Service
metadata:
  name: yarviz-sql-service
  namespace: ingress-yarviz-prod
spec:
  selector:
    app: yarvizprod
  ports:
    - port: 15036
      targetPort: 1433
  type: LoadBalancer